<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Extent Report Suite" duration-ms="15572" started-at="2019-07-03T12:19:52Z" finished-at="2019-07-03T12:20:07Z">
    <groups>
    </groups>
    <test name="Extent Test" duration-ms="15572" started-at="2019-07-03T12:19:52Z" finished-at="2019-07-03T12:20:07Z">
      <class name="com.extent.testcases.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="setup" is-config="true" duration-ms="7414" started-at="2019-07-03T12:19:52Z" finished-at="2019-07-03T12:19:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logotest()[pri:1, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="logotest" duration-ms="42" started-at="2019-07-03T12:19:59Z" finished-at="2019-07-03T12:19:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.extent.testcases.LoginTest.logotest(LoginTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logotest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="teardown" is-config="true" duration-ms="617" started-at="2019-07-03T12:20:00Z" finished-at="2019-07-03T12:20:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="setup" is-config="true" duration-ms="6357" started-at="2019-07-03T12:20:00Z" finished-at="2019-07-03T12:20:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="titleTest()[pri:2, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="titleTest" duration-ms="11" started-at="2019-07-03T12:20:07Z" finished-at="2019-07-03T12:20:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.extent.testcases.LoginTest@4ba2ca36]" name="teardown" is-config="true" duration-ms="607" started-at="2019-07-03T12:20:07Z" finished-at="2019-07-03T12:20:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.extent.testcases.LoginTest -->
    </test> <!-- Extent Test -->
  </suite> <!-- Extent Report Suite -->
</testng-results>
