<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Extent Report Suite" duration-ms="19487" started-at="2019-07-03T12:10:34Z" finished-at="2019-07-03T12:10:54Z">
    <groups>
    </groups>
    <test name="Extent Test" duration-ms="19487" started-at="2019-07-03T12:10:34Z" finished-at="2019-07-03T12:10:54Z">
      <class name="com.extent.testcases.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="setup" is-config="true" duration-ms="10887" started-at="2019-07-03T17:40:34Z" finished-at="2019-07-03T17:40:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logotest()[pri:1, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="logotest" duration-ms="49" started-at="2019-07-03T17:40:45Z" finished-at="2019-07-03T17:40:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.extent.testcases.LoginTest.logotest(LoginTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logotest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="teardown" is-config="true" duration-ms="621" started-at="2019-07-03T17:40:46Z" finished-at="2019-07-03T17:40:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="setup" is-config="true" duration-ms="6561" started-at="2019-07-03T17:40:46Z" finished-at="2019-07-03T17:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="titleTest()[pri:2, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="titleTest" duration-ms="12" started-at="2019-07-03T17:40:53Z" finished-at="2019-07-03T17:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.extent.testcases.LoginTest@2b4a2ec7]" name="teardown" is-config="true" duration-ms="664" started-at="2019-07-03T17:40:53Z" finished-at="2019-07-03T17:40:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.extent.testcases.LoginTest -->
    </test> <!-- Extent Test -->
  </suite> <!-- Extent Report Suite -->
</testng-results>
